image: reg.g.hu.md/hugo/rancher-compose-image:latest

stages:
  # - review
  - push

variables:
  REPO_NAME: hugos-blog

before_script:
  - apk add git 
  - git submodule update --init --recursive

# start_review:
#   stage: review
#   script:
#     - hugo -t hugo-cactus-theme --baseUrl=$(echo https://${REPO_NAME}-${CI_BUILD_REF_SLUG}.now.sh)
#     - URL=$(now -t ${NOW_TOKEN} --static ./public -n ${REPO_NAME}-${CI_BUILD_REF_SLUG})
#     - NOW_URL=$(echo ${URL} | sed s/'http:\/\/'/''/g | sed s/'https:\/\/'//g)
#     - now -t ${NOW_TOKEN} alias set ${NOW_URL} ${REPO_NAME}-${CI_BUILD_REF_SLUG}.now.sh
#   environment:
#     name: review/$CI_BUILD_REF_NAME
#     url: https://$REPO_NAME-$CI_BUILD_REF_SLUG.now.sh
#     on_stop: stop_review
#   only:
#     - branches
#   except:
#     - master

# stop_review:
#   stage: review
#   script:
#     - now rm -t ${NOW_TOKEN} -y ${REPO_NAME}-${CI_BUILD_REF_SLUG}
#   when: manual
#   environment:
#     name: review/$CI_BUILD_REF_NAME
#     action: stop
#   only:
#     - branches
#   except:
#     - master

push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN reg.g.hu.md
    - docker build . --tag blog
    - docker tag reg.g.hu.md/hugo/blog/blog reg.g.hu.md/hugo/blog/blog:$CI_COMMIT_TAG
    - docker push reg.g.hu.md/hugo/blog/blog:latest
    - docker push reg.g.hu.md/hugo/blog/blog:$CI_COMMIT_TAG
  # only:
  # - tags
