image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: reg.g.hu.md/hugo/blog

build:
  stage: build
  image: docker:stable-git
  script:
    - git submodule update --init --recursive
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN reg.g.hu.md
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:latest
    - docker push ${CONTAINER_IMAGE}:latest
