baseURL: /
languageCode: en-us
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
title: Hugo's Blog
theme: simple
paginate: 4
enableGitInfo: true
pygmentsUseClasses: true
relativeURLs: true
minify: true
caches:
  getjson:
    dir: ':resourceDir/json'
    maxAge: -1
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  showMenuItems: 4
  contentTypeName: post
  defaultTheme: light
  showReadingTime: false
  rssFullText: true
  replyViaEmail: true
  replyEmail: blog@hu.md
languages:
  en:
    languageName: English
    weight: 1
    title: Hugo's Blog
    description: >-
      I’m a software engineer, working at Square in Melbourne, Australia. I
      avoid caffeine, tweet, have a few interesting side projects, and try to do
      open source.
    keywords: ''
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: ←  Newer posts
    olderPosts: Older posts →
    lastModDisplay: ''
    dateFormatSingle: Mon Jan 2 2006
    dateFormatList: Mon Jan 2 2006
    params:
      hideReadMore: true
      showMenuItems: 3
      logo:
        logoHomeLink: /
    menu:
      main:
        - identifier: now
          name: Now
          url: /now/
        - identifier: about
          name: About
          url: /about/
        - identifier: archive
          name: Archive
          url: /archive/
  fr:
    languageName: Français
    weight: 2
    title: Le blog d'Hugo
    description: >-
      Je travaille en informatique, à Square, à Melbourne, Australie. 
      Comme passe-temps, je travaille sur des projets open source sur GitHub, 
      prépare du café décaféiner, et m'occupe dans la cuisine.
    keywords: ''
    menuMore: Afficher plus
    writtenBy: Écrit par
    readMore: Lire la suite
    readOtherPosts: Lire d'autres
    newerPosts: ←  Plus récent
    olderPosts: Plus ancien →
    lastModDisplay: ''
    dateFormatSingle: Mon Jan 2 2006
    dateFormatList: Mon Jan 2 2006
    params:
      showMenuItems: 3
      logo:
        logoHomeLink: /
    menu:
      main:
        - identifier: now
          name: Now
          url: /now/
        - identifier: about
          name: About
          url: /about/
        - identifier: archive
          name: Archive
          url: /archive/
